/* AUTHENTICATION */

export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";

export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const AUTH_SIGNUP = "AUTH_SIGNUP";
export const AUTH_SIGNUP_SUCCESS = "AUTH_SIGNUP_SUCCESS";
export const AUTH_SIGNUP_FAILURE = "AUTH_SIGNUP_FAILURE";

export const AUTH_LEAVE = "AUTH_LEAVE";
export const AUTH_LEAVE_SUCCESS = "AUTH_LEAVE_SUCCESS";
export const AUTH_LEAVE_FAILURE = "AUTH_LEAVE_FAILURE";

export const GET_ARTICLES = "GET_ARTICLES";
export const GET_ARTICLES_SUCCESS = "GET_ARTICLES_SUCCESS";
export const GET_ARTICLES_FAILURE = "GET_ARTICLES_FAILURE";

export const AUTH_GET_STATUS = "AUTH_GET_STATUS";
export const AUTH_GET_STATUS_SUCCESS = "AUTH_GET_STATUS_SUCCESS";
export const AUTH_GET_STATUS_FAILURE = "AUTH_GET_STATUS_FAILURE";

export const ARTICLE_SEARCH = "ARTICLE_SEARCH";
export const ARTICLE_SEARCH_SUCCESS = "ARTICLE_SEARCH_SUCCESS";
export const ARTICLE_SEARCH_APPLY = "ARTICLE_SEARCH_APPLY";
export const ARTICLE_SEARCH_FAILURE = "ARTICLE_SEARCH_FAILURE";

export const ARTICLE_POST = "ARTICLE_POST";
export const ARTICLE_POST_SUCCESS = "ARTICLE_POST_SUCCESS";
export const ARTICLE_POST_FAILURE = "ARTICLE_POST_FAILURE";

export const ARTICLE_EDIT = "ARTICLE_EDIT";
export const ARTICLE_EDIT_SUCCESS = "ARTICLE_EDIT_SUCCESS";
export const ARTICLE_EDIT_FAILURE = "ARTICLE_EDIT_FAILURE";




export const ARTICLE_REMOVE ="ARTICLE_REMOVE";
export const ARTICLE_REMOVE_SUCCESS ="ARTICLE_REMOVE_SUCCESS";
export const ARTICLE_REMOVE_FAILURE ="ARTICLE_REMOVE_FAILURE";
